version: '2'

# Bring up a dev environment

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/code
            - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.1-fpm-alpine
        volumes:
            - .:/code
            - ./.docker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    webpack:
        image: jmfirth/webpack
        volumes:
          - .:/app
        command: webpack --watch